# Generated by Django 6.0 on 2026-05-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period_balances', '0004_add_workspace_to_periodbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodbalance',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
