# Generated by Django 6.0 on 2026-03-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('privacy_policy', 'Privacy Policy')], max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('effective_date', models.DateField()),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'legal_documents',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('doc_type',), name='unique_active_legal_document')],
            },
        ),
    ]
